### ISSUE TITLE
can it be used for categorical data multivariate time series ?

### ISSUE THREAD

**Issue by Sandy4321** [Techtonique/ahead_python#4]
* ahead version:
* Python version:
* Operating System: windows

### Description
can it be used for categorical data multivariate time series ?
Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by Sandy4321** [comment]
can it be used for categorical data multivariate time series ?

**Comment by thierrymoudiki** [comment]
Hi @Sandy4321 

I'm not sure that I understand "categorical data multivariate time series". What do you mean?

**Comment by thierrymoudiki** [comment]
@Sandy4321 Shall we close the issue?

**Comment by Sandy4321** [comment]
for exampel
           F1   F2   F2   target 
time1  q     b     c      67
time2   d    b     f      45
time3   a     k     u     12

**Comment by thierrymoudiki** [comment]
@Sandy4321 You can [one-hot encode](https://en.wikipedia.org/wiki/One-hot#Machine_learning_and_statistics) the categorical columns and use the R version's (`ahead::dynrmf`) arguments `xreg_fit`, `xreg_predict`. In Python, it's not possible yet.
